#!/bin/bash

ERR="
	Wrong usage of command, use -h or --help for options
"

HELP="
	DESCRIPTION	-	avant-firewall-enable é um utilitário para re-construção do firewall a 
				partir do comando vindo do AvantData.

	USAGE		- 	avant-firewall-enable [COLLECTOR_IP]

	AUTHOR		-	Daniel Gomes, daniel@avantsec.com.br
"

if [ -z $1 ] ; then

	echo "$ERR"

elif [ $1 == "-h" ] && [ $1 == "--help" ] ; then

	echo "$HELP"

elif [ $1 != "-h" ] || [ $1 != "--help" ] && [ -n $1 ] ; then

	ssh root@$1 'iptables-restore < ./iptables_backup'

fi
